### ISSUE TITLE
`mintPKP()` stopped working recently

### ISSUE THREAD

**Issue by johnnynanjiang** [LIT-Protocol/relay-server#24] opened 2023-06-14 02:31 UTC
`const mintCost = await pkpNft.mintCost();` is failing with the below error

```
Successfully verified Google account { userId: '???' }
in mintPKP
Unable to mint PKP for given Google account {
  err: Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="mintCost()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
      at Logger.makeError (???/lit-protocol-relay-server/node_modules/@ethersproject/logger/lib/index.js:238:21)
      at Logger.throwError (???/lit-protocol-relay-server/node_modules/@ethersproject/logger/lib/index.js:247:20)
      at Interface.decodeFunctionResult (???/lit-protocol-relay-server/node_modules/@ethersproject/abi/lib/interface.js:388:23)
      at Contract.<anonymous> (???/lit-protocol-relay-server/node_modules/@ethersproject/contracts/lib/index.js:395:56)
      at step (???/lit-protocol-relay-server/node_modules/@ethersproject/contracts/lib/index.js:48:23)
      at Object.next (???/lit-protocol-relay-server/node_modules/@ethersproject/contracts/lib/index.js:29:53)
      at fulfilled (???/lit-protocol-relay-server/node_modules/@ethersproject/contracts/lib/index.js:20:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: null,
    code: 'CALL_EXCEPTION',
    method: 'mintCost()',
    data: '0x',
    errorArgs: null,
    errorName: null,
    errorSignature: null,
    address: '0x8F75a53F65e31DD0D2e40d0827becAaE2299D111',
    args: [],
    transaction: {
      data: '0xbdb4b848',
      to: '0x8F75a53F65e31DD0D2e40d0827becAaE2299D111',
      from: '0x535b0dABaF59c90EeeBEf272b5F778C5369a1445'
    }
  }
}
```

I can see transactions stopped 15 hours ago
https://mumbai.polygonscan.com/address/0x535b0dABaF59c90EeeBEf272b5F778C5369a1445

Is `0x8F75a53F65e31DD0D2e40d0827becAaE2299D111` the expected PKP NFT contract address?
```
pkpNftAddress:
		PKP_NFT_ADDRESS || "0x8F75a53F65e31DD0D2e40d0827becAaE2299D111",
```
And the contract looks ok at https://chain.litprotocol.com/address/0x8F75a53F65e31DD0D2e40d0827becAaE2299D111

**Comment by joshLong145** [comment] 2023-06-14 17:25
Closing as the root cause was found and functionality is now as expected.

**Closed by joshLong145** 2023-06-14 17:25 UTC
